# copy to e.g. /etc/dracut.conf.d/90-networkd.conf

# You may add any other networkd files by appending them
# to install_items
install_items+=" /etc/systemd/network/20-wired.network "

# the networkd dracut module is only enabled on request;
# on Ubuntu, /bin/sh is dash and thus we need to include bash explicitly
# such that the root user has a valid shell;
# with the Ubuntu cloud images, the systemd-cryptsetup dracut module
# isn't inluded by default
add_dracutmodules+=" systemd-networkd bash systemd-cryptsetup "

