name: e2e-trigger
run-name: end-to-end test latest greatest fedora and alma
on:
    push:
    pull_request:
jobs:
    e2e-trigger:
        strategy:
            matrix:
                target:
                    - fedora
                    - rawhide
                    - alma
            fail-fast: false
        uses: ./.github/workflows/e2e-base.yml
        with:
            target: ${{ matrix.target }}
